# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

Student_name = input("Enter Student Name: ")
Student_course = input("Enter Student course: ")

total classes = int(input("Enter total classes held: "))
classes_attend = int(input("Enter classes attended: "))

if total_classes <= 0:
  print("Error: Total classes must be greater than 0.")
  elif classes_attended < 0 or classes_attended > total_classes:
    print("Error: Invalid number of attend classes.")
else:
    attendence_precentage =(classes_attended / total_classes) *100

    print("\n----- Attendence Report -----")
    print("Student Name:", student_name)
    print("Course:", student_course)
    print("Attendance Precentage:", round(attendence_precentage, 2), "%")

    if attendance_percentage >= 75:
      print("Allowed for exam")
      else:
        print("Not allowed for exam")